----------------------------------------------------------------------------------------------------
 2016-11-12 16:00:51,208 ERROR - in error_404 [__init__.py:62]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-12 16:01:00,802 ERROR - in error_404 [__init__.py:62]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-12 16:02:02,543 ERROR - in error_404 [__init__.py:62]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-12 16:02:10,299 ERROR - in error_404 [__init__.py:62]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-12 16:02:38,595 ERROR - in error_404 [__init__.py:62]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-12 16:41:37,436 ERROR - in error_404 [__init__.py:62]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-12 16:43:36,873 ERROR - in error_404 [__init__.py:62]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-12 16:43:38,797 ERROR - in error_404 [__init__.py:62]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-12 16:43:53,776 ERROR - in error_404 [__init__.py:62]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-12 16:44:17,609 ERROR - in error_404 [__init__.py:62]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-12 16:44:19,444 ERROR - in error_404 [__init__.py:62]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-12 16:56:06,797 ERROR - in register_routes [__init__.py:55]:
 bp is not blusprint
----------------------------------------------------------------------------------------------------
 2016-11-12 16:56:44,194 ERROR - in register_routes [__init__.py:56]:
 bp is not blusprint
----------------------------------------------------------------------------------------------------
 2016-11-12 16:58:58,238 ERROR - in register_routes [__init__.py:56]:
 bp is not blusprint
----------------------------------------------------------------------------------------------------
 2016-11-12 16:59:13,479 ERROR - in register_routes [__init__.py:56]:
 bp is not blusprint
----------------------------------------------------------------------------------------------------
 2016-11-12 17:02:36,979 ERROR - in register_routes [__init__.py:56]:
 bp is not blusprint
----------------------------------------------------------------------------------------------------
 2016-11-12 17:02:39,173 ERROR - in register_routes [__init__.py:56]:
 bp is not blusprint
----------------------------------------------------------------------------------------------------
 2016-11-12 17:03:02,515 ERROR - in register_routes [__init__.py:56]:
 bp is not blusprint
----------------------------------------------------------------------------------------------------
 2016-11-12 17:03:14,764 ERROR - in register_routes [__init__.py:56]:
 bp is not blusprint
----------------------------------------------------------------------------------------------------
 2016-11-12 17:04:41,506 ERROR - in register_routes [__init__.py:56]:
 bp is not blusprint
----------------------------------------------------------------------------------------------------
 2016-11-12 17:06:14,285 ERROR - in register_routes [__init__.py:56]:
 bp is not blusprint
----------------------------------------------------------------------------------------------------
 2016-11-12 17:06:14,286 ERROR - in register_routes [__init__.py:56]:
 bp is not blusprint
----------------------------------------------------------------------------------------------------
 2016-11-12 19:10:54,824 ERROR - in register_routes [__init__.py:55]:
 bp is not blusprint
----------------------------------------------------------------------------------------------------
 2016-11-13 05:38:26,832 ERROR - in error_404 [__init__.py:65]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-13 05:43:00,003 ERROR - in error_404 [__init__.py:65]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-13 05:43:57,504 ERROR - in error_404 [__init__.py:65]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-13 05:44:16,312 ERROR - in error_404 [__init__.py:65]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-13 05:50:46,780 ERROR - in error_404 [__init__.py:65]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-13 05:52:43,408 ERROR - in error_404 [__init__.py:65]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-13 06:05:03,954 ERROR - in error_404 [__init__.py:65]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-13 11:56:16,348 ERROR - in error_404 [__init__.py:65]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-13 11:56:35,426 ERROR - in error_404 [__init__.py:65]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-14 13:34:05,499 ERROR - in error_404 [__init__.py:65]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-14 13:34:10,252 ERROR - in error_404 [__init__.py:65]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-15 14:27:05,067 ERROR - in error_404 [__init__.py:65]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-15 15:51:27,716 ERROR - in error_404 [__init__.py:65]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-15 21:21:27,253 ERROR - in error_404 [__init__.py:65]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-16 01:33:16,240 ERROR - in error_404 [__init__.py:65]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-16 01:45:52,582 ERROR - in error_404 [__init__.py:65]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-16 01:46:30,728 ERROR - in error_404 [__init__.py:65]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-17 01:50:13,089 ERROR - in error_404 [__init__.py:65]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-20 13:00:31,822 ERROR - in error_404 [__init__.py:65]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-20 14:59:50,856 ERROR - in error_404 [__init__.py:65]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-24 20:48:42,875 ERROR - in error_404 [__init__.py:64]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-24 20:48:42,880 ERROR - in error_404 [__init__.py:64]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-24 20:48:43,129 ERROR - in error_404 [__init__.py:64]:
 404
----------------------------------------------------------------------------------------------------
 2016-11-24 20:48:43,166 ERROR - in error_404 [__init__.py:64]:
 404
